### ISSUE TITLE
Problems after update with docker_manager and webserver-restart

### ISSUE THREAD

**Issue by exetico** [angusmcleod/discourse-quick-messages#10]
Hi'

We're facing problems after quick-messages is updated with docker_manger. It's the only plugin causing problems after restart of the webserver.
![image](https://user-images.githubusercontent.com/3549445/37649035-f34c7ae0-2c30-11e8-83b3-416e648db03b.png)

Are you able to fix it? :-)

The "error" is fixed again, after another restart of the webserver (which happens after the next plugin is updated :smile: We're normally updating the plugins one by one, by pressing the update-button in the docker_manager interface)

**Comment by angusmcleod** [comment]
Yeah, I think this may have just been a temporary issue while you were catching up to the new stylesheet names. Let me know if you see it again.
