### ISSUE TITLE
"No messages yet." on new message

### ISSUE THREAD

**Issue by tchncs** [angusmcleod/discourse-quick-messages#6]
Hi there, i am running `v1.7.0.beta6 +17`.
It turned out that your plugin shows the green dot on new messages 
but the box always shows `No messages yet.` - which is a bit sad :/

**Comment by angusmcleod** [comment]
Hey, are you using the System user (the user created when the instance is created)?

Messages to and from the System user (the user account automatically created when the instance is created) will not appear in this plugin. That account is used to send system notifications to the user, which are not suitable for this plugin.

**Comment by tchncs** [comment]
> Hey, are you using the System user (the user created when the instance is created)?
>
> Messages to and from the System user (the user account automatically created when the instance is created) will not appear in this plugin.

Yes/No since it was a migrated instance from Vanilla i confused this a bit but yeah, i get also those system notes.
But no, i mean regular messages from users.

**Comment by angusmcleod** [comment]
@tchncs hm I'm a little confused. So system messages are showing up. But regular messages are not?

**Comment by tchncs** [comment]
Well, it can be that discourse handles me as the systemuser, but if it is not working there it is also sad. :/

However, i mean this on every kind of message:
![2016-11-01-180611_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/19898860/1cc49f98-a05e-11e6-8258-6d1ff90f44a8.png)

**Comment by tchncs** [comment]
It seems to be fixed yet. :+1:
